### ISSUE TITLE
Is this compatible with Caraya v1.1?

### ISSUE THREAD

**Issue by AndrewHeim** [LabVIEW-Open-Source/Caraya-CLI-extension#1]
Thank you for this tool - it's helped make running Caraya in CI easier.  

We're having some confusion around version compatibility with this library.  On the one hand, the .vipb in the repo says it is compatible with Caraya > 1.0: 
![image](https://user-images.githubusercontent.com/10777768/107293624-3debd080-6a29-11eb-9c1a-1ec05a1b7ba2.png)

But on the other hand, when I build and install it, it gives me this:
![image](https://user-images.githubusercontent.com/10777768/107293673-53f99100-6a29-11eb-89c6-92e458bec4b5.png)

So... I'm not sure where to fix it, since it seems to be compatible yet is telling me to downgrade. 

We tried building it and ignoring the "downgrade" message (so running this against Caraya 1.1) and it ran... but would not return the error that reported "Tests Failed" back to the CLI call.  Instead, it was reporting that tests passed, even while the Junit file was full of failures.  (Note that we changed the assert VIs in our tests to whichever version was installed whenever we ran them.)

I'm not even sure how to submit a pull request, though I'm willing to.  Any thoughts on where to go?  Or if there is a version incompatibility with Caraya 1.1?

**Comment by AndrewHeim** [comment]
(To not be a  DeverCoder9  - https://xkcd.com/979/)

After another test and a bit more digging, this looks like a Caraya behavior change.

The Batch Tests.vi that ships with Caraya no longer returns an error if the tests fail - only if the test execution had an internal error in executing them.

I think this behavioral change happens somewhere in **Craya.lvlib:Test Runner.lvclass:Execute Tests** (v1.0) versus **Craya.lvlib:Test Runner.lvclass:Run** (v1.1) .

**Comment by francois-normandin** [comment]
Hi @AndrewHeim , 

The downgrade request is because when you build the package using VIPM, it wants to set your IDE configuration to the package version as it is listed in the VIPC file (package configuration). 

If you want to build it yourself, from source, this is indeed what you'd have to do so that your final package's dependencies match the listed configuration. To prevent the downgrade, you'd first have to change the VIPC file to the version you are using.

You might have good reason for rebuilding the package from source, such as having to conform to such a policy for security or audit reasons. However, if you're only looking at installing the library, you can get the VIP file directly from the release page here: 
https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/releases/tag/1.0.0.2

**Comment by francois-normandin** [comment]
@AndrewHeim  Can you open another issue if the behavior change you noted causes the CLI tool to fail with Caraya 1.1?
I have not tried it with the latest.
