### ISSUE TITLE
Can we make the inputs for output path and source path to allow for relative paths?

### ISSUE THREAD

**Issue by stagg54** [LabVIEW-Open-Source/Caraya-CLI-extension#5]
My main use case for using the CLI is for CI/CD. Having absolute path makes that more difficult.

The G-CLI toolkit itself has a VI for handling this.
![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/898da848-a2e5-4f84-b8e2-b7a3f4d00b18)

It is as simple as adding this inline.

The working path comes from opening the G-CLI connection.
![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/d5d97093-9456-4671-a0d3-7764a2ebc7f7)

You would just replace the 2 string to path primitives with the G-CLI Converter.
![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/e2f8063e-0bb4-4dc7-a7cd-bdff4dd6044d)

**Comment by stagg54** [comment]
Note add this should be backwards compatible. I use it in all my G-CLI tools and it's pretty easy. It takes either an absolute or relative path with no problem.

**Comment by stagg54** [comment]
I am using the latest version of G-CLI. I noticed this is pegged to an older version, so that VI may not be available.

Here's the contents: It is pretty simple and should be easy to recreate.

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/59c7d632-6e33-4267-940c-937a44678a33)

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/6b2ee568-2dc2-443b-8dfd-29fd28c4bd32)

**Comment by stagg54** [comment]
Actually looks like it was added in 2.1

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/5c9bd290-1da1-477c-ac48-907541b6ea51)

**Comment by francois-normandin** [comment]
I`ll use my own methods so to also handle URL-encoded characters, and multiple variants for all different OS.

`..\path\my%20report.txt` == `..\path\my report.txt` (resolve as relative to work-dir)

This is not expected to be very much used since the quotes allow spaces, but if (ever) arguments are passed from a web request, there would be less of a need to ensure that the URL-encoded variables are massaged before between sent to the CLI interface.

Apart from supporting symbolic paths, I think this should be comprehensive.
![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/11728548/5ae772ce-2289-412c-8ee9-c3563e66221d)

**Comment by francois-normandin** [comment]
Version 2.x will resolve relative paths to WorkDir as shown here, where the testResults are saved to desktop, with a path relative to work-dir.

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/11728548/fff6a9f8-98f9-4b92-82ce-e3ba00dfe707)

**Comment by francois-normandin** [comment]
URL encoding is working fine too. 

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/11728548/abc7789e-a90f-4110-926b-50dce9ea4334)
